### ISSUE TITLE
App crashes when start button is pressed.

### ISSUE THREAD

**Issue by Mayavan** [Navigine/Android-Fake-Mock-Location-Tricks#1]
I get the below error message when mLocationManager.addTestProvider() is called in MockLocationImpl.java

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.navigine.mockgps, PID: 9938
    java.lang.IllegalArgumentException: Provider "gps" already exists
        at android.os.Parcel.createException(Parcel.java:2075)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at android.location.ILocationManager$Stub$Proxy.addTestProvider(ILocationManager.java:2022)
        at android.location.LocationManager.addTestProvider(LocationManager.java:1461)
        at com.navigine.mockgps.MockLocationImpl.setMock(MockLocationImpl.java:43)
        at com.navigine.mockgps.MockLocationImpl.access$000(MockLocationImpl.java:10)
        at com.navigine.mockgps.MockLocationImpl$1.run(MockLocationImpl.java:27)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.LocationManagerService.addTestProvider(LocationManagerService.java:3536)
        at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:958)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

**Comment by MrCrambo** [comment]
@Mayavan could you please provide info about your android version?

**Comment by Mayavan** [comment]
My phone is running Android 10

**Comment by MrCrambo** [comment]
@Mayavan Looks like you have another app which added test provider, aren't you?

**Comment by Mayavan** [comment]
@MrCrambo  Yes, I do. Does this mean this app will not work when I have another app?

**Comment by MrCrambo** [comment]
Sure, it will not work, when you have another app. By the way we will fix this exception throwing and will show another message!

Thanks for bug report!
